In [1]:
# %tensorflow_version 2.x
import tensorflow as tf


In [2]:
tf.compat.v1.disable_eager_execution()
tf.__version__

'2.3.0-dev20200515'

In [3]:
hello= tf.constant("Hello World!")
print(hello)
hello

Tensor("Const:0", shape=(), dtype=string)


<tf.Tensor 'Const:0' shape=() dtype=string>

In [4]:
with tf.compat.v1.Session() as session:
    result = session.run(hello)

In [5]:
print(result)

b'Hello World!'


In [6]:
const=tf.constant(10)
matrix=tf.fill((5,5),10)
zeros=tf.zeros((5,5))
ones=tf.ones((5,5))

In [7]:
print(const,matrix,zeros,ones)

all_combine=[const,matrix,zeros,ones]

Tensor("Const_1:0", shape=(), dtype=int32) Tensor("Fill:0", shape=(5, 5), dtype=int32) Tensor("zeros:0", shape=(5, 5), dtype=float32) Tensor("ones:0", shape=(5, 5), dtype=float32)


In [8]:
session=tf.compat.v1.InteractiveSession()

In [9]:
for i in all_combine:
    print(i)
    print(session.run(i))

Tensor("Const_1:0", shape=(), dtype=int32)
10
Tensor("Fill:0", shape=(5, 5), dtype=int32)
[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]
Tensor("zeros:0", shape=(5, 5), dtype=float32)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Tensor("ones:0", shape=(5, 5), dtype=float32)
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
a=tf.constant(10)
b=tf.constant(20)
c = a + b
print(session.run(c))

30


In [11]:
tf.compat.v1.get_default_graph()

In [12]:
graph= tf.Graph()
graph

In [13]:
mat1=tf.random_uniform_initializer((5,5),0,10)

In [17]:
# var1 = tf.Variable(initial_value=mat1)